[package]
name = "athar-adv/replicated-registry"
version = "1.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors = ["athar_adv"]
exclude = ["rokit.toml"]
homepage = "https://athar-adv.github.io/ReplicatedRegistry2"
repository = "https://github.com/athar-adv/ReplicatedRegistry2"

[dependencies]
